# **Preprocess Sample Dataset with Basic Pre-Processing Techniques**

This notebook demonstrates essential data preprocessing techniques, including handling missing values, encoding categorical data, splitting the dataset, and feature scaling. It shows how to prepare a sample dataset for machine learning models, ensuring clean, well-processed data for training and evaluation.

#### Importing the libraries

In [196]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### Importing the dataset

In [197]:
# import datsaet
dataset = pd.read_csv('Data.csv')
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


#### Split datset into dipendemnt variables Y and the indipendent variables X

In [198]:
# split as dipendemnt variables Y and the indipendent variables X
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1:].values

In [199]:
print('x values\n', X)

x values
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [200]:
print('y values\n', y.reshape(-1))

y values
 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


#### Handling missing data

*  **Imputation**: Fill missing values using mean, median, mode, or more complex methods like K-Nearest Neighbors (KNN) or regression.

*  **Deletion**: Remove rows or columns with missing values, especially if the missingness is high or the data is not critical.

In [201]:
# Check for missing values in each column
missing_values_per_column = dataset.isnull().sum()

# Display the number of missing values for each column
print(missing_values_per_column)

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [202]:
# Import the SimpleImputer
from sklearn.impute import SimpleImputer

# mean value
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# fit for 'age' and 'salary'
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [203]:
print('new X\n',X)

new X
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


#### Encoding categorical data

* **Label Encoding**: Convert categorical values into numerical values (e.g., assigning 0, 1, 2 to categories).

* **One-Hot Encoding**: Create binary columns for each category (e.g., a column for each category with 0 or 1 values).

##### Encoding the Independent Variable

In [204]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# here 0 is the column that we are going to apply onehot encoding
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# fit with X
X = np.array(ct.fit_transform(X))

In [205]:
# new matrix including onehotencoding part
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


##### Encoding the Dependent Variable

In [206]:
from sklearn.preprocessing import LabelEncoder

# encode y labels to 1 and 0
le = LabelEncoder()
y = le.fit_transform(y.reshape(-1))

In [207]:
# new y
print(y)

[0 1 0 0 1 1 0 1 0 1]


#### Splitting the dataset into the Training set and Test set

**Training and Testing Split**: Divide your dataset into training and testing sets to evaluate model performance.

In [208]:
# import train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [209]:
# Print training X set
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [210]:
# Print test X set
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [211]:
# Print training Y set
print(y_train)

[0 1 0 0 1 1 0 1]


In [212]:
# Print test y set
print(y_test)

[0 1]


### Feature Scaling

There are two types
**Standardisation** and **Normalisation**

`Standardisation` is good for all tasks but `Normalisation` is good for normal distributed data.


This process should be do after spliting the datset to train and test. because of avoiding data leakage.


In [213]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# No need to apply standadscaler to onehot encoded values.
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [214]:
# print x train after doing standardscaling
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [215]:
# print x test after doing standardscaling
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
